spring:
  application:
    name: orders
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:8081/realms/eurotransit}
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:http://localhost:8081/realms/eurotransit/protocol/openid-connect/certs}
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/eurotransit
    username: eurotransit
    password: password

server:
  port: 8084

management:
  otlp:
    metrics:
      export:
        enabled: false
